name: Deploy to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  buildx-storefront-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t jackharrhy/storefront-frontend \
            ./storefront-frontend/ \
            --push

  buildx-storefront-discord:
    needs: [buildx-storefront-frontend]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t jackharrhy/storefront-discord \
            ./storefront-discord/ \
            --push
