name: Deploy to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-storefront-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Dockerhub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.17
      with:
        name: jackharrhy/storefront-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: storefront-frontend/Dockerfile
        workdir: storefront-frontend

  build-storefront-discord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Dockerhub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.17
      with:
        name: jackharrhy/storefront-discord
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: storefront-discord/Dockerfile
        workdir: storefront-discord
