name: Deploy to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  buildx-storefront-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t jackharrhy/storefront-frontend \
            ./storefront-frontend/ \
            --push

  build-storefront-discord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Dockerhub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.17
      with:
        name: jackharrhy/storefront-discord
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: storefront-discord/Dockerfile
